export const typeColors = {
  normal: { bg: 'bg-[#A8A878]', text: 'text-white' },
  fire: { bg: 'bg-[#F08030]', text: 'text-white' },
  water: { bg: 'bg-[#6890F0]', text: 'text-white' },
  grass: { bg: 'bg-[#78C850]', text: 'text-white' },
  electric: { bg: 'bg-[#F8D030]', text: 'text-black' },
  ice: { bg: 'bg-[#98D8D8]', text: 'text-black' },
  fighting: { bg: 'bg-[#C03028]', text: 'text-white' },
  poison: { bg: 'bg-[#A040A0]', text: 'text-white' },
  ground: { bg: 'bg-[#E0C068]', text: 'text-black' },
  flying: { bg: 'bg-[#A890F0]', text: 'text-white' },
  psychic: { bg: 'bg-[#F85888]', text: 'text-white' },
  bug: { bg: 'bg-[#A8B820]', text: 'text-white' },
  rock: { bg: 'bg-[#B8A038]', text: 'text-white' },
  ghost: { bg: 'bg-[#705898]', text: 'text-white' },
  dragon: { bg: 'bg-[#7038F8]', text: 'text-white' },
  dark: { bg: 'bg-[#705848]', text: 'text-white' },
  steel: { bg: 'bg-[#B8B8D0]', text: 'text-black' },
  fairy: { bg: 'bg-[#EE99AC]', text: 'text-black' }
}; 